# CircleCI configuration file.
# @author - Ali Shanaakh.
#

version: 2
jobs:
  build:
    machine: true
    environment:
      REGISTRY: quay.io
      DOCKER_IMG: quay.io/shal/openalpr-web
    steps:
      - checkout
      - run:
          name: Login in Dockerhub
          command: |
            docker login ${REGISTRY} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
      - run:
          name: Build docker image
          command: |
            docker build -t openalpr-web .
      - run:
          name: Build docker image
          command: |
            docker tag openalpr-web ${DOCKER_IMG}:$(echo $CIRCLE_SHA1 | cut -c -7)
            docker tag openalpr-web ${DOCKER_IMG}
      - run:
          name: Push docker images
          command: |
            docker push ${DOCKER_IMG}:$(echo $CIRCLE_SHA1 | cut -c -7)
            docker push ${DOCKER_IMG}

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
